### ISSUE TITLE
Error when change the view to detail view

### ISSUE THREAD

**Issue by mmasmoudi** [dwenzel/t3events#53]
Hi again,
Another error occurs when i change the view to detail view on backend.

Uncaught TYPO3 Exception
#1: PHP Warning: array_key_exists() expects parameter 2 to be array, string given in /kunden/181543_70794/rp-hosting/6010/7010/...../typo3_src-7.6.15/typo3/sysext/core/Classes/Utility/ArrayUtility.php line 144 (More information)

t3events	0.31.1
t3calendar	0.2.0
I already cleared cache from installtool but no change

**Comment by dwenzel** [comment]
This is a warning only. The exception is thrown because you are runnig TYPO3 in debug mode. You can circumvent it by turning debug output off (in Install Tool enable Configuration Preset _Live_)

This error occurs in a PHP class of the TYPO3 core. My call to ArrayUtility::isValidPath is correct.
I will investigate if I can avoid in anyway.

cheers
Dirk

**Comment by mmasmoudi** [comment]
Thanks for the reply, ok when i enabled the live view the warning is gone, but i want really use the detail view in another page, when i click on a event item, the detail view is showing on same page and i don't get redirected to the Detail view page which contain a plugin record (Event Detail view). I have setup the correct view in both pages.

**Comment by dwenzel** [comment]
Did you configure the detail page on tab _Pages_ of your list view plugin?
The default is the current page

**Comment by dwenzel** [comment]
The initial issue has been resolved (in develop branch, commit 8b70c0a) and will be available with the next version of t3events (0.32.0).

**Comment by mmasmoudi** [comment]
Thanks a lot for the new version, i will try it.

**Comment by mmasmoudi** [comment]
Yes i have already configured the plugin for detail view. In commit 8b70c0a i see only changing version number and did not resolve the detail view issue.

**Comment by dwenzel** [comment]
This change prevents the warning in ArrayUtility. That is the topic of this issue.

Concerning the link to the detail page.
The detail page id can be configured in two ways:
* By setting it in the list plugin (Tab _Pages_) or
* in TypoScript

Actually the templates contained old values. I changed it in the development branch (@ 190ff4a8).
```
-		<f:link.action action="show" arguments="{event: event}" pageUid="{settings.event.single.pid}">
+		<f:link.action action="show" arguments="{event: event}" pageUid="{settings.detailPid}">
```
<img width="943" alt="event_detail" src="https://cloud.githubusercontent.com/assets/712458/23837008/90ab03ae-0781-11e7-8d0c-d01dac4b033e.png">

**Comment by mmasmoudi** [comment]
Yes, i was using the backend configuration detail page, no typoscript added. Thanks i will try the updated version of the files.
