### ISSUE TITLE
Can't see events - minimal configuration

### ISSUE THREAD

**Issue by ste101** [dwenzel/t3events#67]
Hello,
I tried to use t3events but I'm not able to show events. I can only see the message 'No events'.
I installed t3events, added the static template and created an event with a future date. I added a plugin after that.
I tried to set the record storage page and/or setting the constand storagePid to the folder where the events resists.

What is missing to show a list of events?

Thanks in advance
Stephan

**Comment by dwenzel** [comment]
Hi Stephan,
sorry for the late reply - I was (and am) on vacations.
The error described above had been introduced in version 0.34.0 (see #66) and fixed in version 0.35.0. 
The latter was already released 6 days ago (here on github) but not uploaded to the TER.
I did this just now.

Please check the latest version - I'm sorry for any inconvenience.

cheers
Dirk

**Comment by ste101** [comment]
Hello Dirk,
thank you very much for your answer. I hope you have nice holydays.
I made an update to 0.35 but still can't see any event in list view.
I set no constrains. Only 'sort by date'

Regards
Stephan

**Comment by dwenzel** [comment]
great - thank you for your feedback
